
import streamlit as st
st.set_page_config(page_title="QuLab: Operational Risk Measurement", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab: Operational Risk Measurement")
st.divider()

page = st.sidebar.selectbox(label="Navigation", options=["Data Loading & Analysis", "Risk Profile Grid", "Analytics & Visualizations"])
if page == "Data Loading & Analysis":
    from application_pages.data_loading_and_analysis import run_data_loading_and_analysis
    run_data_loading_and_analysis()
elif page == "Risk Profile Grid":
    from application_pages.risk_profile import run_risk_profile
    run_risk_profile()
elif page == "Analytics & Visualizations":
    from application_pages.analytics_and_visualizations import run_analytics_and_visualizations
    run_analytics_and_visualizations()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
